### ISSUE TITLE
Strona główna

### ISSUE THREAD

**Issue by seohhe** [akai-org/onepage#1]
![home](https://user-images.githubusercontent.com/17861616/32252256-e467e442-be94-11e7-9be6-41efe4f9f9b4.png)

**Comment by tomaszgil** [comment]
Drobne rzeczy do poprawki:
- zmniejszyć odrobinę logo akai
- powiększyć button do rezerwacji miejsca (żeby był dokładnie taki jak ten od kontaktu)
- sprawdzić wyświetlanie buttonów w Google Chrome
- zwiększyć odstęp między strzałką a 'Dowiedz się więcej'
- podpiąć w. w. przycisku event scrollowania do sekcji o wydarzeniu
