### ISSUE TITLE
Link do kalendarza

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/onepage#22]
Gdzieś tam, pewnie po kliknięciu daty, ale to trzeba zaznaczyć, fajnie byłoby zrobić link dodaj do kalendarza, który działałby jak na tej stronie, otwierając już wypełniony formularz kalendarza.

https://www.codeeurope.pl/pl/agenda

**Comment by tomaszgil** [comment]
Świetny pomysł. Pod datą możemy zrobić link 'Dodaj do kalendarza', po kliknięciu w który pod spodem rozwinie się blok z dwoma linkami do Google Calendar i iCal (podobnie jak sekcja o prelekcjach) albo tak jak jest w linku wyżej, linki te zastąpią pierwotny.
