### ISSUE TITLE
Dynamiczne ładowanie danych i generowanie zawartości

### ISSUE THREAD

**Issue by rrudol** [akai-org/onepage#29]
Aktualnie jesteśmy w stanie generować świetnie wyglądające statyczne strony. Niestety edycja zawartości wymaga od autora pobrania repozytorium o odpowiedniej wersji i przy każdej zmianie zbudowanie projektu na nowo. Podobnie, wprowadzenie poprawki do komponentu wymaga aktualizacji każdego page'a.

Chciałem zaproponować stworzenie prostego skryptu, który odczytywałby dane z pliku JSON, a następnie wygenerowałby dynamicznie zawartość strony. To rozwiązanie pozwoliłoby nam utrzymywać tylko jedną wersję kodu i uniezależniłoby nas od danych i pozwoliło stworzyć oddzielny edytor lub chociaż formularz do ich tworzenia.

Dane mogłyby być ładowane z zewnętrznego serwisu, który wystawiałby je przez api.

**Comment by marcinlawnik** [comment]
Może coś a'la https://github.com/janl/mustache.js?
Jedyny problem jaki widzę to brak obsługi logiki - dynamiczne dodawanie sekcji.

```
JavaScript's dot notation may be used to access keys that are properties of objects in a view.

View:

{
  "name": {
    "first": "Michael",
    "last": "Jackson"
  },
  "age": "RIP"
}
Template:

* {{name.first}} {{name.last}}
* {{age}}
Output:

* Michael Jackson
* RIP
```

**Comment by rrudol** [comment]
Dokładnie, mustache (albo handlebars) świetnie nadawałyby się do tworzenia markupu komponentów.
Jeśli chodzi o dynamiczne generowanie sekcji, możemy to napisać z ręki, nie powinno być dużo pracy.

**Comment by tomaszgil** [comment]
Zostanie rozwiązane przez pull request #36
