### ISSUE TITLE
Dołączyć czcionki do projektu

### ISSUE THREAD

**Issue by tomaszgil** [akai-org/onepage#33]
Zamiast załączać czcionki przez link w html, powinny one być dodane do repozytorium.

**Comment by rrudol** [comment]
mamy w skrypcie budującym [font-magician](https://github.com/jonathantneal/postcss-font-magician)
https://github.com/akai-org/onepage/blob/master/gulp/tasks/styles.js
zatem wystarczy zrobić plik _fonts.scss i tam je zadeklarować, a same dołączą się się z Google Fonts

**Comment by tomaszgil** [comment]
Okej, w takim razie issue do zamknięcia.
