### ISSUE TITLE
Integracja z kalendarzami

### ISSUE THREAD

**Issue by tomaszgil** [akai-org/onepage#35]
Dodać funkcjonalność zapisywania wydarzeń w kalendarzach (Google i Apple) do przycisków w sekcji Date and Venue. Komponent powinien otrzymać dane konfiguracyjne z jsona, przetworzyć je w taki, sposób aby po kliknięciu w odpowiedni link otworzyła się strona z możliwością zapisania wydarzenia w odpowiednim kalendarzu.

- [x] integracja z kalendarzem Google
- [x] integracja z kalendarzem Apple

**Comment by Herdu** [comment]
Integracja z Apple Calendar wymaga wygenerowania pliku (.ics) z zaproszeniem do wydarzenia i umożliwienie pobierania tego pliku pod przyciskiem w sekcji Date and Venue. Taki plik trzeba by dołączać razem z danymi konfiguracyjnymi z Jsona.

**Comment by tomaszgil** [comment]
@rrudol w kontekście tego co napisał @Herdu trzeba podjąć decyzję czy wspieramy też kalendarz od Apple.

**Comment by rrudol** [comment]
Jestem za wspieraniem, ale tylko przyszłych wydarzeń.

**Comment by Herdu** [comment]
Ewentualnie można użyć biblioteki js do generowania .ics, jeśli wklejanie gotowego pliku nie jest satysfakcjonujące

**Comment by tomaszgil** [comment]
Rozwiązane przez #44.
