### ISSUE TITLE
Minifikacja JS

### ISSUE THREAD

**Issue by tomaszgil** [akai-org/onepage#37]
CI wyrzuca błąd na minifikacji JS, na razie rezygnujemy z niej. 
Trzeba naprawić ten problem - włączyć minifikacje i zapewnić poprawność builda.

https://travis-ci.org/akai-org/onepage/jobs/271825203

**Comment by rrudol** [comment]
Testy już przechodzą, będzie fixed po mergu https://github.com/akai-org/onepage/pull/54

**Comment by tomaszgil** [comment]
@rrudol Fixed, można zamknąć?
