### ISSUE TITLE
Sekcja ze szczegółami poszczególnych wydarzeń

### ISSUE THREAD

**Issue by seohhe** [akai-org/onepage#4]
![strona_glowna](https://cloud.githubusercontent.com/assets/9485365/24870608/259ec238-1e17-11e7-8f5d-96f0fbf12a91.jpg)
Miejsce na opis prelekcji (prawdopodobnie bez żadnych przycisków)

**Comment by tomaszgil** [comment]
Drobne poprawki:
- dorzucić wrapper na całość (żeby osiągnąć takie zachowanie, jak sekcja o wydarzeniu)
- po pierwszym breakpoincie przenieść godzinę do góry, równo z tytułem (ewentualnie pod spodem może być to podkreślenie jako border-bottom)
- po drugim breakpoincie wyrzucić horyzontalną linię pomarańczową (btw. tutaj już marginesy ładnie działają)

**Comment by tomaszgil** [comment]
Wykonano, do zamknięcia.
