### ISSUE TITLE
Formularz kontaktowy

### ISSUE THREAD

**Issue by seohhe** [akai-org/onepage#5]
![strona_glowna](https://cloud.githubusercontent.com/assets/9485365/24870699/78a30bb0-1e17-11e7-9cb7-4370ce32e11d.jpg)
Formularz kontaktowy, trzeba b edzie dodać jeszcze inputa do wpisania wiadomości

**Comment by tomaszgil** [comment]
Poprawki:
- zmniejszyć wszystko do takich rozmiarów jakie były dla font-size: 10px :) - zmieniliśmy na 16px.
